---
- name: Pull and run Docker image
  hosts: dev
  become: true
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "your_container_name"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        ports:
          - "host_port:container_port"
        volumes:
          - "/host/path:/container/path"
        restart_policy: always
